language: ruby
rvm:
  - 2.1.1
addons:
  postgresql: "9.3"
service_name: travis-ci
before_script:
  - psql -c 'create database inventories_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
